# Generated by Django 4.2.5 on 2024-01-05 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_Notes',
            fields=[
                ('Share_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('Note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.notes')),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='Auth.customuser')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to='Auth.customuser')),
            ],
        ),
    ]
